config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  root to: "tweets#index"
  resources :tweets do
    member do
      get 'atlas'
    end
    member do
      get 'seek'
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :prefecture

  validates :image, presence: {message:'選択してください'}
  validates :title, :explain, :city, :house_number, presence: true
  validates :category_id, :prefecture_id, numericality: {other_than: 1, message:'を選択してください' }


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tweet, only: [:edit, :update, :destroy, :show, :atlas, :seek]
  
  def index
    @tweets = Tweet.includes(:user).order(created_at: :DESC)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if user_signed_in? && @tweet.user == current_user
      @tweet.destroy
      redirect_to root_path
    elsif @tweet.user != current_user
      redirect_to root_path
    end
  end

  def edit 
    if current_user == @tweet.user
      render :edit
    elsif current_user != @tweet.user
      redirect_to root_path
    else
      redirect_to user_sessions_path
    end
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def atlas
  end

  def seek
  end

  private 

  def tweet_params
    params.require(:tweet).permit(:image, :title, :explain, :category_id, :prefecture_id, :city, :house_number).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/atlas.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap&libraries=&v=weekly"defer></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <style type="text/css">
       #map {
        height: 90%;
      }
      html,
      body {
        height: 80%;
        margin: 0;
        padding: 0;
      }
      #floating-panel {
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: "Roboto", "sans-serif";
        line-height: 30px;
        padding-left: 10px;
      }
    </style>
    <script>
      function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
          zoom: 10,
          center: { lat: 35.18028, lng: 136.90667 },
        });
        const geocoder = new google.maps.Geocoder();
        const infowindow = new google.maps.InfoWindow();
        document.getElementById("submit").addEventListener("click", () => {
          geocodeLatLng(geocoder, map, infowindow);
        });
      }

      function geocodeLatLng(geocoder, map, infowindow) {
        const input = document.getElementById("latlng").value;
        const latlngStr = input.split(",", 2);
        const latlng = {
          lat: parseFloat(latlngStr[0]),
          lng: parseFloat(latlngStr[1]),
        };
        geocoder.geocode({ location: latlng }, (results, status) => {
          if (status === "OK") {
            if (results[0]) {
              map.setZoom(11);
              const marker = new google.maps.Marker({
                position: latlng,
                map: map,
              });
              infowindow.setContent(results[0].formatted_address);
              infowindow.open(map, marker);
            } else {
              window.alert("結果が見つかりません");
            }
          } else {
            window.alert("失敗しました: " + status);
          }
        });
      }
    </script>
  </head>
  <body>
    <div id="floating-panel">
      <input id="latlng" type="text" value= "<%= @tweet.image.metadata[:latitude] %>,<%= @tweet.image.metadata[:longitude] %>" />
      <input id="submit" type="button" value="検索する" />
    </div>
    <div id="map"></div>

  </body>
</html>

app/views/tweets/edit.html.erb
<div class="contents row">
 
  <div class="container">
    <h2>編集する</h2>
    <div class="content">
      <%= form_with(model: @tweet, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
    <div class="img-upload">
      <label class="form-image">
      <%= f.file_field :image,class:"image-default",id:'tweet_image' %>
      <span class="image-file">投稿画像を変更</span>
      <input type="file" class="hidden">
      </label>
      <div id="image-list"></div>
    </div>

    <div class="tweets-title">
      <%= f.text_field :title, placeholder: "タイトル" %>
    </div>

    <div class="tweets-explain">
      <%= f.text_area :explain, placeholder: "text", rows: "10" %>
    </div>

    <div class="tweets-category">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"tweet-category"}) %>
    </div>

    <div class="tweets-prefecture">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    </div>

     <div class="tweets-city">
      <%= f.text_field :city, placeholder: "市町村" %>
    </div>

    <div class="tweets-house_number">
      <%= f.text_field :house_number, placeholder: "番地(任意)" %>
    </div>

    <div class="actions">
    <input type="submit" name="tweetedit" value="投稿" class="button">
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="tweet-main">
  <div class="tweet-upper">
     <% @tweets.each do |tweet| %>
      <div class="tweet-image">
      <%=link_to image_tag(tweet.image), tweet_path(tweet.id) %>
      </div>
    <div class="tweet-table">
    <table>
      <tr>
        <th class="tweet-titles">タイトル</th>
        <th class="tweet-title"><%= tweet.title %></th>
      </tr>
      <tr>
        <th class="tweet-prefectures">撮影地</th>
        <th class="tweet-prefecture"><%= tweet.prefecture.name %></th>
      </tr>
      <tr>
        <th class="tweet-nicknames">投稿者</th>
        <th class="tweet-nickname"><%= tweet.user.nickname %></th>
      </tr>
    </table>
    <% end %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
 
  <div class="container">
    <h2>投稿する</h2>
    <div class="content">
      <%= form_with(model: @tweet, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
    <div class="img-upload">
      <label class="form-image">
      <%= f.file_field :image,class:"image-default",id:'tweet_image' %>
      <span class="image-file">投稿画像を選択</span>
      <input type="file" class="hidden">
      </label>
      <div id="image-list"></div>
    </div>

    <div class="tweets-title">
      <%= f.text_field :title, placeholder: "タイトル" %>
    </div>

    <div class="tweets-explain">
      <%= f.text_area :explain, placeholder: "text", rows: "10" %>
    </div>

    <div class="tweets-category">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"tweet-category"}) %>
    </div>

    <div class="tweets-prefecture">
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    </div>

     <div class="tweets-city">
      <%= f.text_field :city, placeholder: "市町村" %>
    </div>

    <div class="tweets-house_number">
      <%= f.text_field :house_number, placeholder: "番地" %>
    </div>

    <div class="actions">
    <input type="submit" value="投稿"name="tweetpost" class="button">
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/tweets/seek.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geocoding Service</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script
      src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
    <style type="text/css">
      #map {
        height: 90%;
      }
      html,
      body {
        height: 80%;
        margin: 0;
        padding: 0;
      }
      #floating-panel {
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: "Roboto", "sans-serif";
        line-height: 30px;
        padding-left: 10px;
      }
    </style>
    <script>
      function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
          zoom: 10,
          center: { lat: 35.18028, lng: 136.90667 },
        });
        const geocoder = new google.maps.Geocoder();
        document.getElementById("submit").addEventListener("click", () => {
          geocodeAddress(geocoder, map);
        });
      }

      function geocodeAddress(geocoder, resultsMap) {
        const address = document.getElementById("address").value;
        geocoder.geocode({ address: address }, (results, status) => {
          if (status === "OK") {
            resultsMap.setCenter(results[0].geometry.location);
            new google.maps.Marker({
              map: resultsMap,
              position: results[0].geometry.location,
            });
          } else {
            alert(
              "Geocode was not successful for the following reason: " + status
            );
          }
        });
      }
    </script>
  </head>
  <body>
    <div id="floating-panel">
      <input id="address" type="textbox" value="<%= @tweet.prefecture.name %><%= @tweet.city %><%=@tweet.house_number %>" />
      <input id="submit" type="button" value="検索する" />
    </div>
    <div id="map"></div>
  </body>
</html>

app/views/tweets/show.html.erb
<div class="tweet-show">
  <div class="tweet-box">
    <% if user_signed_in? && current_user == @tweet.user %>
     <div id="wrapper">
        <p class="btn-gnavi">
          <span></span>
          <span></span>
          <span></span>
        </p>
        <nav id="tweet-navi">
          <ul class="menu">
            <li><%= link_to '一覧に戻る', root_path, class: "a" %></li>
            <li><%= link_to '編集', edit_tweet_path, method: :get, class: "a" %></li>
            <li><%= link_to '削除', tweet_path(@tweet.id), method: :delete, class: "tweet-red-btn" %></li>
          </ul>
        </nav>
      </div>
    <% end %>
    <h2 class="title">
      <%= @tweet.title %>
    </h2>  
    <div class="tweet-img">
      <%= image_tag @tweet.image, class:"tweet-box-img" %>
    </div>
    <div class="tweet-table">
    <table>
      <tr>
        <th class="tweet-expalins">詳細</th>
        <th class="tweet-expalin"><%= @tweet.explain %></th>
      </tr>
      <tr>
        <th class="tweet-categorys">カテゴリー</th>
        <th class="tweet-category"><%= @tweet.category.name %></th>
      </tr>
      <tr>
        <th class="tweet-prefectures">都道府県</th>
        <th class="tweet-prefecture"><%= @tweet.prefecture.name %></th>
      </tr>
      <tr>
        <th class="tweet-citys">市町村</th>
        <th class="tweet-city"><%= @tweet.city %></th>
      </tr>
      <tr>
        <th class="tweet-house_numbers">番地</th>
        <th class="tweet-house_number"><%= @tweet.house_number %></th>
      </tr>
    </table>
    </div>
    <% if @tweet.image.metadata[:latitude].present? && @tweet.image.metadata[:longitude].present? %>
    <div class="map-select">
      <%= link_to '画像から検索',atlas_tweet_path, class: "button" %>
    </div>
    <% end %>
    <div class="map-select">
      <%= link_to '住所から検索',seek_tweet_path, class: "button" %>
    </div>
  </div>
  <div class="tweet-comments">
    <% if user_signed_in? %>
      <%= form_with(model:[@tweet, @comment], local: true) do |f| %>
        <div class="comment-area">
        <%= f.text_area :text, placeholder: "コメントする", rows: "3", cols: "100" %>
        </div>
        <div class="actions">
          <input type="submit" name="commentpost" value="送信" class="button">
        </div>
      <% end %>
      <% else %>
        <strong><p class="comment-message">※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comment">
      <h2>＜コメント一覧＞</h2>
      <% if @comments %>
        <% @comments.each do |comment|%>
          <p class="comment-text">
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}"%>:</strong>
            <%= comment.text %>
          </p>
          <% if user_signed_in? && current_user == comment.user%>
          <div class="delete">
            <%=link_to 'コメント削除', tweet_comment_path(comment.tweet.id, comment.id), method: :delete, class:"comment-delete" %>
          </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>