config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    registrations: 'users/registrations'
  }
  root to: "tweets#index"
  resources :tweets do
    member do
      get 'atlas'
    end
    member do
      get 'seek'
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mapimage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header__bar row">
        <div class="nav__left">
          <a href="/">Mapimage</a>
        </div>
        <% if user_signed_in? %>
        <div class="nav__right">
          <div class="user-name">
             <div class="image-header">
             <img src=<%= current_user.image%> class="top_image">
             </div>
             <div class="name">
              こんにちは!<br>
              <%= current_user.nickname + "さん" %>
             </div>
          </div>
          <ul class="user__info">
            <li class="users-info">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
              <%= link_to "マイページ", "/users/#{current_user.id}", class: "post" %>
              <%= link_to "ユーザー編集", edit_user_registration_path, class: "post" %>
              <%= link_to "投稿する", new_tweet_path, class: "post" %>
            </li>
          </ul>
          </div>
        <% else %>
         <div class="nav__right">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>
          